kind: pipeline
name: tests

steps:
- name: lint
  image: miki725/pre-commit
  depends_on:
    - clone

- name: python3.8
  image: python:3.8
  commands:
    - pip install tox
    - tox -e $(tox -l | grep py38 | paste -sd ",")
  environment:
    ADDITIONAL_COVERAGE_FLAGS: --cov-report=xml
  depends_on:
    - clone

- name: python3.7
  image: python:3.7
  commands:
    - pip install tox
    - tox -e $(tox -l | grep py37 | paste -sd ",")
  depends_on:
    - clone

- name: python3.6
  image: python:3.6
  commands:
    - pip install tox
    - tox -e $(tox -l | grep py36 | paste -sd ",")
  depends_on:
    - clone

- name: python2.7
  image: python:2.7
  commands:
    - pip install tox
    - tox -e $(tox -l | grep py27 | paste -sd ",")
  depends_on:
    - clone

- name: pypy
  image: pypy:2.7
  commands:
    - pip install tox
    - tox -e $(tox -l | grep pypy- | paste -sd ",")
  depends_on:
    - clone

- name: pypy3
  image: pypy:3.6
  commands:
    - pip install tox
    # ignore django latest as pypy3.6 does not have updated sqlite yet
    # and django fails to correctly create db in earlier sqlite versions
    # >>> sqlite3.sqlite_version_info
    # (3, 16, 2)
    - tox -e $(tox -l | grep pypy3- | grep -v latest | paste -sd ",")
  depends_on:
    - clone

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
      - '*.xml'
    required: true
  depends_on:
    - python3.8

trigger:
  trigger:
    ref:
    - refs/heads/master
    - refs/pull/*/head

---
kind: pipeline
name: release

steps:
- name: release
  image: python:3.8
  environment:
    TWINE_USERNAME:
      from_secret: pypi_username
    TWINE_PASSWORD:
      from_secret: pypi_token
  commands:
    - make install INSTALL_FILE=requirements-release.txt INSTALL_LOG=/dev/null
    - make release

trigger:
  event:
    - tag
