dist: xenial
sudo: false
branches:
  only:
    - master
cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
addons:
  apt_packages:
    - sqlite3

language: python
python:
  - "3.6-dev"
  - "3.7-dev"
  - "2.7"
  - "pypy"
  - "pypy3.5-7.0"

install:
  - pip install tox-travis
  - pip install coveralls==1.1

script: tox

after_success: coveralls
